#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ESPDroid.Resource", IsApplication=true)]

namespace ESPDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int homeImage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int homeImage2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int ImageView1 = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int btnSave = 2131099654;
			
			// aapt resource value: 0x7f060037
			public const int fragmentContainer = 2131099703;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06002d
			public const int linearLayout2 = 2131099693;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayoutModel = 2131099674;
			
			// aapt resource value: 0x7f060036
			public const int plotview1 = 2131099702;
			
			// aapt resource value: 0x7f06002e
			public const int rdo1 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int rdo2 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int rdo3 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int rdo4 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int rdo5 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int rdo6 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int rdo7 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int rdo8 = 2131099701;
			
			// aapt resource value: 0x7f060009
			public const int scrollView1 = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int switch1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int switch2 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int switch3 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int switch4 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int switch5 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int switch6 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int switch7 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int switch8 = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int textView1 = 2131099675;
			
			// aapt resource value: 0x7f06002c
			public const int textView2 = 2131099692;
			
			// aapt resource value: 0x7f06000b
			public const int txtAboutText = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int txtAboutTitle = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int txtCreditsText = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int txtCreditsTitle = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int txtHelpText = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int txtHelpTitle = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int txtIP = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int txtIPText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int txtIntroOne = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int txtIntroTwo = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int txtPort = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int txtPortText = 2131099652;
			
			// aapt resource value: 0x7f060011
			public const int txtSpecialThanksText = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int txtSpecialThanksTitle = 2131099664;
			
			// aapt resource value: 0x7f06001c
			public const int txts1 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int txts2 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int txts3 = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int txts4 = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int txts5 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int txts6 = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int txts7 = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int txts8 = 2131099690;
			
			// aapt resource value: 0x7f06001d
			public const int txtv1 = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int txtv2 = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int txtv3 = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int txtv4 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int txtv5 = 2131099685;
			
			// aapt resource value: 0x7f060027
			public const int txtv6 = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int txtv7 = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int txtv8 = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_tab_home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_tab_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_tab_relays = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_tab_sensors = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int IntroOne = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int IntroTwo = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int about = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int credits = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int help = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int specialThanks = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
